# Generated by Django 4.2.6 on 2023-10-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_name', models.CharField(max_length=50, verbose_name='название пункта меню')),
                ('menu_item_reference', models.CharField(max_length=100, verbose_name='ссылка на пункт меню')),
                ('parent_menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='django_app.menu', verbose_name='родительский пункт меню')),
            ],
        ),
    ]
