# Generated by Django 4.2.6 on 2023-10-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_menu_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='level',
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_item_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ссылка на пункт меню'),
        ),
    ]
